# Generated by Django 4.2.29 on 2026-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(help_text='Comma-separated skills e.g. Tires, Engine, AC')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('service_radius_km', models.FloatField(default=15.0)),
                ('is_available', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to='mechanic_docs/')),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mechanic_profiles',
            },
        ),
    ]
