# Generated by Django 4.2.29 on 2026-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated skills e.g. Tires, Engine, AC'),
        ),
    ]
