# Generated by Django 4.2.29 on 2026-03-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('tow', 'Tow Service')], default='mechanic', max_length=20),
        ),
    ]
